---
apiVersion: v1
kind: Namespace
metadata:
  name: envoy-gateway
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: envoy-gateway
  namespace: envoy-gateway
spec:
  type: "oci"
  interval: 1h
  url: oci://docker.io/envoyproxy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway
spec:
  interval: 10m
  chart:
    spec:
      chart: gateway-helm
      version: "v1.4.2"
      sourceRef:
        kind: HelmRepository
        name: envoy-gateway
      interval: 10m
  values:
    config:
      envoyGateway:
        extensionApis:
          enableBackend: true
        gateway:
          controllerName: gateway.envoyproxy.io/gatewayclass-controller
        logging:
          level:
            default: "info"
          provider:
            type: "Kubernetes"
