apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/selfsigned-issuer
  - ../../components/openbao-dev
  - ../../components/openbao-dev-ui

patches:
  - path: envoy-nodeport.yml
    target:
      kind: EnvoyProxy
      name: proxy-config
